### ISSUE TITLE
Option to remove the fake title bar?

### ISSUE THREAD

**Issue by TorutheRedFox** [milbits/oldcord#122]
For those who have a native titlebar, having an extra titlebar within the window is kinda... silly, and it's ridiculous that the designers of the refresh didn't consider this.

An option to hide it would be nice

**Comment by milbits** [comment]
it's hidden on web and linux

**Comment by medalzzz** [comment]
Can I have a picture of that @TorutheRedFox? Mine is hidden

**Comment by TorutheRedFox** [comment]
(i use it to make it match the theme i have on the rest of my system :P)

**Comment by milbits** [comment]
```css
.platform-win {
	.base_c48ade {
		grid-template-areas: "titleBar titleBar titleBar" "notice notice notice" "guildsList channelsList page";
		grid-template-rows: [top] 0px [titlebarEnd] min-content [page] 0px [end] !important;
	}
```
in quickcss
it should work, idk if it does

**Comment by TorutheRedFox** [comment]
the discord logo and caption buttons are still there

![Image](https://github.com/user-attachments/assets/5f42b644-f093-4cb6-99b3-8fbc9ec9000d)

**Comment by milbits** [comment]
.bar_c38106 .title_c38106 {
		display: none;
	}
	.bar_c38106 .trailing_c38106 {
		top: 33px !important;
	}
	.scroller_ef3116 {
		padding-top: 2px !important;
	}

**Comment by TorutheRedFox** [comment]
and also
```CSS
.winButtons_c38106
{
        display: none;
}
```

**Comment by milbits** [comment]
true

**Comment by milbits** [comment]
can't help you there right now as it's super late and im laying on my bed, super comfortable an shi

**Comment by TorutheRedFox** [comment]
fairr

**Comment by milbits** [comment]
they should let you react with anything on GitHub not just 6 emojis

**Comment by TorutheRedFox** [comment]
full CSS to hide the titlebar on Windows for anyone that stumbles upon this in the future:

```CSS
.platform-win {
	.base_c48ade {
		grid-template-areas: "titleBar titleBar titleBar" "notice notice notice" "guildsList channelsList page";
		grid-template-rows: [top] 0px [titlebarEnd] min-content [page] 0px [end] !important;
	}
	.title_c38106
	{
		display: none;
	}
	.winButtons_c38106
	{
		display: none;
	}
	.bar_c38106 .trailing_c38106 {
		top: 33px;
	}
	.scroller_ef3116 {
		padding-top: 2px;
	}
	.bar_c38106[data-windows=true] {
		display: none;
	}
	body
	{
		--custom-app-top-bar-height: 0px;
	}
}
```

**Comment by TorutheRedFox** [comment]
wait one sec that brought back the title bar in settings

**Comment by TorutheRedFox** [comment]
yep

here's the version with the properly fixed settings titlebar btw

```CSS
.platform-win {
	.base_c48ade {
		grid-template-areas: "titleBar titleBar titleBar" "notice notice notice" "guildsList channelsList page";
		grid-template-rows: [top] 0px [titlebarEnd] min-content [page] 0px [end] !important;
	}
	.title_c38106
	{
		display: none;
	}
	.winButtons_c38106
	{
		display: none;
	}
	.bar_c38106 .trailing_c38106 {
		top: 30px;
	}
	.systemBar_c38106 {
		height: 0px;
		min-height: 0px;
		background-color: transparent;
	}
	.scroller_ef3116 {
		padding-top: 2px;
	}
	body
	{
		--custom-app-top-bar-height: 0px;
	}
}
```
