### ISSUE TITLE
voiceBar overlaps with the header

### ISSUE THREAD

**Issue by Umgak** [milbits/oldcord#124]
Hello,
Discord's new voiceBar object overlaps with the server's header. It's supposed to be anchored to the bottom, but appears on the top of the list instead with OldCord.

![Image](https://github.com/user-attachments/assets/72226e49-8bfc-436d-9fcf-73ff873c23d7)

I simply hid it using QuickCSS:
```css
[class*="voiceBar__"] {
  display:none;
}
```
You may want to make a similar change in the theme itself.
