### ISSUE TITLE
Can you add the ability to disable display names and pronouns?

### ISSUE THREAD

**Issue by tavvvvvvvvvvvvvv** [milbits/oldcord#15]
profiles like this look really bad with the new display names and pronouns, could you add the ability to remove them?

![image](https://github.com/milbits/oldcord/assets/138950887/8fb4fc65-8863-4889-b087-09faaa1eae83)

**Comment by tavvvvvvvvvvvvvv** [comment]
is there a way to do this for the user profiles too? it stays the same

![image](https://github.com/milbits/oldcord/assets/138950887/b25c7382-2923-40cf-94e1-7e65c4918cf7)

**Comment by milbits** [comment]
```css
.container-3g15px .text-lg-semibold-UQkeZc{
	display: none
}
.customStatus-3qYNe4{
	padding-top: 25px
}

.pronouns-RGQpyK{
	display: none
}
.info-3ddo6z .discriminator-hnHkyt {
	color: var(--interactive-active);
	width: 320px;
	left: 87px;
	font-size: 18px;
	line-height: 26px;
}

.headerTop-1PNKck > .badgeList-2aoHPw{
	top: 21px
}
```
![image](https://github.com/milbits/oldcord/assets/51537072/8cb2662b-583c-4fda-a344-7163a850589f)
