### ISSUE TITLE
'Search' text is not vertically centered.

### ISSUE THREAD

**Issue by lindenkron** [milbits/oldcord#184]
Examples:
![Image](https://github.com/user-attachments/assets/79d1fa9c-2df3-499a-9a08-ce363f02d770)
![Image](https://github.com/user-attachments/assets/cacd8f31-c76d-404e-8797-baf6b3f3a590)

Adding the following seems to fix the issue:
```css
.search__97492 .DraftEditor-root .public-DraftEditor-content,
.search__97492 .DraftEditor-root .public-DraftEditorPlaceholder-root {
    padding: 2px 2px 0px 2px !important;
}

.searchBar__97492 {
    align-items: center;
}
```

After:
![Image](https://github.com/user-attachments/assets/9cd4be7c-3139-4522-ad11-78307e6b4211)
![Image](https://github.com/user-attachments/assets/af7e9407-658b-44c4-9162-9b332eae2813)
