### ISSUE TITLE
Bugged background when selecting Dark and/or Onyx as Appearance

### ISSUE THREAD

**Issue by StudentSerai1181201811** [milbits/oldcord#197]
When selecting Light or Ash, the theme works as expected like so:

![Image](https://github.com/user-attachments/assets/c3789175-2c88-4352-bb99-b6680dedb382)

However, when using Dark or Onyx, the theme looks like the following:

![Image](https://github.com/user-attachments/assets/29e3d5a6-6393-498a-95bb-9b3a6deffa11)

From dev tools, the background-color becomes transparent specifically for these appearance themes.

The nitro themes don't seem to be affected.

Affected css is redesign.css, I'm not using other themes, just oldcord.

I'm on the browser version of Discord with the Vencord web extension.

My Quick CSS is this:
```css
/* Pre-refresh font */
    body{
        --font-primary: "gg sans", Whitney, "Helvetica Neue", Helvetica, Arial, sans-serif;
        --font-display: "gg sans", Whitney, "Helvetica Neue", Helvetica, Arial, sans-serif !important;
        --font-headline: "gg sans", Whitney, "Helvetica Neue", Helvetica, Arial, sans-serif;
    }

/* Pre-refresh blurple */
    /* New Messages bar */
    .newMessagesBar__0f481, .newTopicsBarContainer__0f481{
        background-color: rgb(88, 101, 242);
    }
    /* Buttons */
    :is(.lookFilled__201d5.colorBrand__201d5,.lookFilled__201d5.colorBrand__201d5:disabled){
        background-color: rgb(88, 101, 242);

        &:hover {
            background-color: rgb(70, 84, 192) !important;
        }

        &:active {
            background-color: rgb(58, 72, 163) !important;
        }
    }
    /* Toggle buttons */
    .container__87bf1 .input__87bf1 {
        &:checked:before {
            background: rgb(88, 101, 242);
        }
    }
```

I have the ClientTheme plugin too but turning it off doesn't fix it either.
