### ISSUE TITLE
[Request] Old Twemoji support

### ISSUE THREAD

**Issue by toydotgame** [milbits/oldcord#22]
[Earlier this year, Discord switched their branch of Twemoji](https://twitter.com/DiscordPreviews/status/1640809457423732763) from [twitter/twemoji](https://github.com/twitter/twemoji) to [jdecked/twemoji](https://github.com/jdecked/twemoji). This is a pretty basic change AFAIK, but I don't know how easy stuff will be to change (given certain, uh, ~~Elon things<sup>TM</sup> \*cough cough\*~~). ([Diffs here](https://github.com/twitter/twemoji/compare/master...jdecked:twemoji:main))

The old `:pleading_face:` emoji was kinda iconic ngl, and the new ones – although technically more uniform to other platforms – really kinda lack that old Discord feel imo.

**Comment by milbits** [comment]
heres the import
```css
@import url("https://milbits.github.io/oldcord/src/components/oldEmojis.css");
```
or just raw if you prefer that i guess
```css
/*plead 🥺*/
[src*="f3f159b921f71864327c.svg"]{
	content: url("https://milbits.github.io/oldcord/src/assets/oldPlead.svg")
}
/*holding back 🥹*/
[src*="f2e5d8cf525a4550e1b1.svg"]{
	content: url("https://milbits.github.io/oldcord/src/assets/oldHoldingBack.svg")
}
```
