### ISSUE TITLE
[FEATURE] Old Context Menu

### ISSUE THREAD

**Issue by andriemc** [milbits/oldcord#25]
What about the old context menu?

![image](https://github.com/milbits/oldcord/assets/72381315/92b483fa-3f0b-4d5b-8518-ea24d9832c13)

Screenshot from [this video](https://youtu.be/wxpQGEfT-bo)

**Comment by andriemc** [comment]
How close is this?

![image](https://github.com/milbits/oldcord/assets/72381315/d9f2e5ba-1544-469e-b8a3-72a2ce2bf90a)

```css
.focused__27621 {
    background-color: var(--background-modifier-hover) !important;
}
```
